version: 2
updates:
  # Web应用依赖更新
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # 桌面应用依赖更新
  - package-ecosystem: "npm"
    directory: "/apps/desktop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # 移动应用依赖更新
  - package-ecosystem: "pub"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # 后端API依赖更新
  - package-ecosystem: "npm"
    directory: "/backend/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # 后端Admin依赖更新
  - package-ecosystem: "npm"
    directory: "/backend/admin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # GitHub Actions依赖更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

