name = "anywallpaper-web"
main = "dist/_worker.js"
compatibility_date = "2025-10-20"

routes = [
  { pattern = "anywallpaper.net/*", zone_name = "anywallpaper.net" },
  { pattern = "www.anywallpaper.net/*", zone_name = "anywallpaper.net" }
]
