name = "anywallpaper-admin"
main = "src/index.ts"
compatibility_date = "2025-10-20"

# KV 命名空间
[[kv_namespaces]]
binding = "WALLPAPER_CACHE"
id = "4eca079022f14b6183fbc87069cc7deb"

# 路由配置（部署时启用）
routes = [
  { pattern = "admin.anywallpaper.net/*", zone_name = "anywallpaper.net" }
]
