name: Deploy Web (Workers)

on:
  push:
    branches: [main, master]
    paths:
      - 'apps/web/**'
      - '.github/workflows/deploy-web.yml'

jobs:
  deploy:
    name: Deploy Next.js to Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (root)
        run: npm install

      - name: Install dependencies (web)
        run: |
          cd apps/web
          npm install

      - name: Build Next.js for Workers
        run: |
          cd apps/web
          npm run cf:build

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/web'
          command: deploy

