name: Deploy to Cloudflare

on:
  push:
    branches: [main, master]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-cloudflare.yml'

jobs:
  deploy-api:
    name: Deploy API Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd backend/api
          npm install
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'backend/api'
          command: deploy

  deploy-admin:
    name: Deploy Admin Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd backend/admin
          npm install
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'backend/admin'
          command: deploy

